### PR TITLE
ADuCM3029_Asset_Health: Replace old adxl372 driver with noos one

### PR DESCRIPTION
**Pull request by mirceacaprioru**
This patch replaces the old ADXL372 driver with the one developed for noOs.

Signed-off-by: Mircea Caprioru <mircea.caprioru@analog.com>

### CODE REVIEW

**Comment by adrimbarean** [comment]
The Release version of the project does not include in the compiler path the include folder.

**Comment by adrimbarean** [comment]
The Release version of the project defines __ADUCM302x__ in adi_processor.h:51:0 for DFP 3.2.0 and as a define flag for the compiler, which generates a warning.

**Comment by mirceacaprioru** [comment]
Changelog V1->V2
- fix release configuration

**Comment by mirceacaprioru** [comment]
Will merge today if there are no objections.

**Pull request merged**
